#!/bin/bash -ex

# set localhost to be always be first nameserver
echo "nameserver 127.0.0.1" >> /etc/resolvconf/resolv.conf.d/head
echo "search domain.lan" >> /etc/resolvconf/resolv.conf.d/head

# symlink for samba documentation
ln -s /usr/share/doc/samba-doc/htmldocs /var/www/samba

# setup cups certificate
/usr/lib/inithooks/firstboot.d/16cups-sslcert

# tweak tkl-webcp
sed -i "s|padding: 5pt 8px;|padding: 5pt 8px 25pt 8px;|" /var/www/css/base.css

chmod +x /usr/lib/inithooks/bin/sambaconf_add.sh
chmod +x /usr/lib/inithooks/bin/sambaconf_join.sh

systemctl unmask samba-ad-dc
