#!/bin/bash -e
# set samba domain, realm and administrator password

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

# support partially preseeded headless deployments
if [ -z "$APP_REALM" ]; then
    if [ -n "$APP_PASS" ] && [ -n "$APP_DOMAIN" ]; then
        APP_REALM="$APP_DOMAIN.lan"
    fi
fi
if [ -z "APP_JOIN" ]; then
    APP_JOIN="false"
    APP_JOIN_NS="false"
fi

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/domain-controller.py --domain="$APP_DOMAIN" --realm="$APP_REALM" --pass="$APP_PASS" --join="$APP_JOIN" --join_ns="$APP_JOIN_NS"

